services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-backend
    ports:
      - "8085:8085"
    volumes:
      - blog_data:/root/data
    environment:
      - DB_PATH=/root/data/blog.db
      - GIN_MODE=release
      - RECOVERY_MODE=${RECOVERY_MODE:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8085/api/categories"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=https://b.zli.li/api
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  blog_data:
    driver: local