services:
  blog:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://b.zli.li/api}
    container_name: blog-unified
    ports:
      - "80:80"
    volumes:
      - blog_data:/app/data
    environment:
      - DB_PATH=/app/data/blog.db
      - GIN_MODE=release
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://b.zli.li/api}
      - RECOVERY_MODE=${RECOVERY_MODE:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/api/categories"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  blog_data:
    driver: local